/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cellsbook;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.*;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
/**
 *
 * @author PRINCE
 */
public class inmate_search extends javax.swing.JFrame {
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form inmate_search
     */
    public inmate_search() {
        initComponents();
        section();
    }
    /**
     *
     */
     
 String imagePath = null ;
    //resize image
    
    public ImageIcon ResizeImage(String imagePath, byte[] pic){
        
        ImageIcon myImage = null;
        
        if (imagePath != null){ 
            
            myImage = new ImageIcon(imagePath);
            
        } else {
            
            myImage = new ImageIcon(pic);
            
               }
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lpic1.getWidth(), lpic1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        
        
        return image;
        
                    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        lpic1 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txt_officer = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txt_crime = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_property = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txt_h = new javax.swing.JTextField();
        txt_native = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        tid2 = new javax.swing.JTextField();
        occup1 = new javax.swing.JTextField();
        mscombo2 = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        addr2 = new javax.swing.JTextArea();
        gcombo2 = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        date4 = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        tel3 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        txt_search1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        bt_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INMATE MANAGEMENT SYSTEM (TANOSO POLICE STATION)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 43));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inmate Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel44.setText("Picture");
        jPanel4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 60, 30));

        lpic1.setBackground(new java.awt.Color(204, 204, 204));
        lpic1.setOpaque(true);
        jPanel4.add(lpic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 19, 182, 100));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel48.setText("Officer");
        jPanel4.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, 30));

        txt_officer.setEditable(false);
        txt_officer.setBackground(new java.awt.Color(204, 255, 255));
        txt_officer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_officerActionPerformed(evt);
            }
        });
        jPanel4.add(txt_officer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 160, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel49.setText("Property found on Accused");
        jPanel4.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 190, 30));

        txt_crime.setEditable(false);
        txt_crime.setBackground(new java.awt.Color(204, 255, 255));
        txt_crime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_crimeActionPerformed(evt);
            }
        });
        jPanel4.add(txt_crime, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 220, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel50.setText("Crime/ Offence");
        jPanel4.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 90, 30));

        txt_property.setBackground(new java.awt.Color(204, 255, 255));
        txt_property.setColumns(20);
        txt_property.setRows(5);
        jScrollPane1.setViewportView(txt_property);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, 80));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 460, 440));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inmate Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.setName("Teachers Info"); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Booking No,");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 33, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Hour:");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 59, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Name: ");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 90, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Marita Status");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 171, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Native of:");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setText("Gender");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 209, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("Age");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("Permanent Address");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 34));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("Contact Address");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 34));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("Occupation:");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 34));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("Date ");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 116, -1, 34));

        txt_h.setEditable(false);
        txt_h.setBackground(new java.awt.Color(204, 255, 255));
        txt_h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hActionPerformed(evt);
            }
        });
        jPanel3.add(txt_h, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 59, 113, -1));

        txt_native.setEditable(false);
        txt_native.setBackground(new java.awt.Color(204, 255, 255));
        txt_native.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nativeActionPerformed(evt);
            }
        });
        jPanel3.add(txt_native, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 236, -1));

        name2.setEditable(false);
        name2.setBackground(new java.awt.Color(204, 255, 255));
        name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name2ActionPerformed(evt);
            }
        });
        jPanel3.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 90, 223, -1));

        tid2.setEditable(false);
        tid2.setBackground(new java.awt.Color(204, 255, 255));
        tid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tid2ActionPerformed(evt);
            }
        });
        jPanel3.add(tid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 33, 113, -1));

        occup1.setEditable(false);
        occup1.setBackground(new java.awt.Color(204, 255, 255));
        occup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occup1ActionPerformed(evt);
            }
        });
        jPanel3.add(occup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 236, -1));

        mscombo2.setBackground(new java.awt.Color(204, 255, 255));
        mscombo2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mscombo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Divorce", "Married", " " }));
        jPanel3.add(mscombo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 236, -1));

        addr2.setBackground(new java.awt.Color(204, 255, 255));
        addr2.setColumns(20);
        addr2.setRows(5);
        jScrollPane3.setViewportView(addr2);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 236, 60));

        gcombo2.setBackground(new java.awt.Color(204, 255, 255));
        gcombo2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gcombo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel3.add(gcombo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 236, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setText("or");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        date4.setEditable(false);
        date4.setBackground(new java.awt.Color(204, 255, 255));
        date4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date4ActionPerformed(evt);
            }
        });
        jPanel3.add(date4, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 123, 152, -1));

        txt_age.setEditable(false);
        txt_age.setBackground(new java.awt.Color(204, 255, 255));
        txt_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ageActionPerformed(evt);
            }
        });
        jPanel3.add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 40, -1));

        tel3.setEditable(false);
        tel3.setBackground(new java.awt.Color(204, 255, 255));
        tel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel3ActionPerformed(evt);
            }
        });
        jPanel3.add(tel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 236, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel42.setText("Telephone Number");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, 34));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 440));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SEARCH BY :");

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel53.setText("Booking N0.  :");

        txt_search.setBackground(new java.awt.Color(204, 204, 255));
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel54.setText("NAME  :");

        txt_search1.setBackground(new java.awt.Color(204, 204, 255));
        txt_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search1ActionPerformed(evt);
            }
        });
        txt_search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search1KeyReleased(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("SEARCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        bt_back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_back.setText("Back");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_search, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_search1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(bt_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 870, 100));

        setSize(new java.awt.Dimension(887, 634));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hActionPerformed

    private void txt_nativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nativeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nativeActionPerformed

    private void name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name2ActionPerformed

    private void tid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tid2ActionPerformed

    private void occup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occup1ActionPerformed

    private void date4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date4ActionPerformed

    private void txt_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageActionPerformed

    private void tel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tel3ActionPerformed

    private void txt_officerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_officerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_officerActionPerformed

    private void txt_crimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_crimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_crimeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // CODE FOR SEARCH TEACHER
        try {
           con=Connection1.ConnectDB();
           String sql = "Select * from inmate Where book_no='"+tid2.getText()+"'";

            pst=con.prepareStatement(sql);
            rs=  pst.executeQuery();
            if (rs.next()){

                tid2.setText("book_no");
                
                String add1=rs.getString("lname");
                name2.setText(add1);
                
                String com100=rs.getString("m_status");
                gcombo2.addItem(com100);
                
                String com10=rs.getString("gender");
                gcombo2.addItem(com10);

                String add2=rs.getString("dof");
                date4.setText(add2);
                
                String add3=rs.getString("address");
                addr2.setText(add3);
                
                String add4=rs.getString("officer");
                txt_officer.setText(add4);

                byte[] img = rs.getBytes("pic");
                
                 ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(lpic1.getWidth(), lpic1.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);
                    lpic1.setIcon(newImage);

                String add6=rs.getString("age");
                txt_age.setText(add6);

                String add16=rs.getString("telephone");
                txt_age.setText(add16);

                String add8=rs.getString("crime");
                txt_crime.setText(add8);

                String add60=rs.getString("hr");
                txt_age.setText(add60);
                

                String add9=rs.getString("property");
                txt_property.setText(add9);

                String add11=rs.getString("native");
                txt_native.setText(add11);

                String com12=rs.getString("occup");
                occup1.setText(com12);

            }

        }catch( Exception ex){

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void txt_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
           con=Connection1.ConnectDB();
           String sql = "Select * from inmate Where fname='"+txt_search1.getText()+"'";

            pst=con.prepareStatement(sql);
            rs=  pst.executeQuery();
            if (rs.next()){

                tid2.setText("book_no");
                
                String add1=rs.getString("lname");
                name2.setText(add1);
                
                String com100=rs.getString("m_status");
                gcombo2.addItem(com100);
                
                String com10=rs.getString("gender");
                gcombo2.addItem(com10);

                String add2=rs.getString("dof");
                date4.setText(add2);
                
                String add3=rs.getString("address");
                addr2.setText(add3);
                
                String add4=rs.getString("officer");
                txt_officer.setText(add4);

                byte[] img = rs.getBytes("pic");
                
                 ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(lpic1.getWidth(), lpic1.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);
                    lpic1.setIcon(newImage);

                String add6=rs.getString("age");
                txt_age.setText(add6);

                String add16=rs.getString("telephone");
                tel3.setText(add16);

                String add8=rs.getString("crime");
                txt_crime.setText(add8);

                String add60=rs.getString("hr");
                txt_h.setText(add60);
                

                String add9=rs.getString("property");
                txt_property.setText(add9);

                String add11=rs.getString("native");
                txt_native.setText(add11);

                String com12=rs.getString("occup");
                occup1.setText(com12);

            }

        }catch( Exception ex){

        }

        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
          dispose();
        mainC m = new mainC();
        m.setVisible(true);

    }//GEN-LAST:event_bt_backActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased

        try {
           con=Connection1.ConnectDB();
           String sql = "Select * from inmate Where book_no=?";

            pst=con.prepareStatement(sql);
            
            pst.setString(1, txt_search.getText());
             rs=  pst.executeQuery();
            if (rs.next()){

                //tid2.setText("book_no");
                
                String add1=rs.getString("lname");
                name2.setText(add1);
                
                String com100=rs.getString("m_status");
                gcombo2.addItem(com100);
                
                String com10=rs.getString("gender");
                gcombo2.addItem(com10);

                String add2=rs.getString("dof");
                date4.setText(add2);
                
                String add3=rs.getString("address");
                addr2.setText(add3);
                
                String add4=rs.getString("officer");
                txt_officer.setText(add4);

                byte[] img = rs.getBytes("pic");
                
                 ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(lpic1.getWidth(), lpic1.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);
                    lpic1.setIcon(newImage);

                String add6=rs.getString("age");
                txt_age.setText(add6);

                String add16=rs.getString("telephone");
                tel3.setText(add16);

                String add8=rs.getString("crime");
                txt_crime.setText(add8);

                String add60=rs.getString("hr");
                txt_h.setText(add60);
                

                String add9=rs.getString("property");
                txt_property.setText(add9);

                String add11=rs.getString("native");
                txt_native.setText(add11);

                String com12=rs.getString("occup");
                occup1.setText(com12);

            }

        }catch( Exception ex){

        }

        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search1KeyReleased

        
          try {
           con=Connection1.ConnectDB();
           String sql = "Select * from intate Where name=?";

            pst=con.prepareStatement(sql);
            
            pst.setString(1, txt_search1.getText());
             rs=  pst.executeQuery();
            if (rs.next()){

                tid2.setText("book_no");
                
                String add1=rs.getString("name");
                name2.setText(add1);
                
                String com100=rs.getString("m_status");
                gcombo2.addItem(com100);
                
                String com10=rs.getString("gender");
                gcombo2.addItem(com10);

                String add2=rs.getString("dof");
                date4.setText(add2);
                
                String add3=rs.getString("address");
                addr2.setText(add3);
                
                String add4=rs.getString("officer");
                txt_officer.setText(add4);

                byte[] img = rs.getBytes("pic");
                
                 ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(lpic1.getWidth(), lpic1.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);
                    lpic1.setIcon(newImage);

                String add6=rs.getString("age");
                txt_age.setText(add6);

                String add16=rs.getString("telephone");
                tel3.setText(add16);

                String add8=rs.getString("crime");
                txt_crime.setText(add8);

                String add60=rs.getString("hr");
                txt_h.setText(add60);
                

                String add9=rs.getString("property");
                txt_property.setText(add9);

                String add11=rs.getString("native");
                txt_native.setText(add11);

                String com12=rs.getString("occup");
                occup1.setText(com12);

            }

        }catch( Exception ex){

        }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inmate_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inmate_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inmate_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inmate_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inmate_search().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addr2;
    private javax.swing.JButton bt_back;
    private javax.swing.JTextField date4;
    private javax.swing.JComboBox gcombo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lpic1;
    private javax.swing.JComboBox mscombo2;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField occup1;
    private javax.swing.JTextField tel3;
    private javax.swing.JTextField tid2;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_crime;
    private javax.swing.JTextField txt_h;
    private javax.swing.JTextField txt_native;
    private javax.swing.JTextField txt_officer;
    private javax.swing.JTextArea txt_property;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_search1;
    // End of variables declaration//GEN-END:variables

    private void section() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("police.png")));
    }
}
