/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cellsbook;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.*;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author PRINCE
 */
public class court_appear extends javax.swing.JFrame {
    DefaultTableModel dm;
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form court_appear
     */
    public court_appear() {
        initComponents();
        Update_table();
        section();
        
        //createcol();
    }

    private void createcol (){
        
        dm=(DefaultTableModel) table_c.getModel();
        dm.addColumn("DATE AND TIME");
        dm.addColumn("COURT");
        dm.addColumn("OFFICER");
    }
    private void Update_table ()
{
        try {
            con=Connection1.ConnectDB();
            String sql = "select date_time ,court_name, officer from court";
            PreparedStatement pstm =con.prepareStatement(sql);
            rs=pstm.executeQuery(sql);
            table_c.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception ex) {
         JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    
}

    
        private void Reset()
{
    txtinmate_name.setText("");
    txtattorney.setText("");
    
    
    txtcourt.setText("");
    txtofficer.setText("");
    txtlocation.setText("");
  txtjudge.setText("");
   
    
     txtpros.setText("");
     txtcity.setText("");
     txttrans.setText("");
    
    txtcomment.setText("");
    
    txttime.setText("");
    
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtinmate_name = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtattorney = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtlocation = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtofficer = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcourt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtjudge = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttrans = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtpros = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtcomment = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_c = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btdelete = new javax.swing.JButton();
        btadd = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("INMATE MANAGEMENT SYSTEM (TANOSO POLICE STATION)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 43));

        txtinmate_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinmate_nameActionPerformed(evt);
            }
        });
        txtinmate_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtinmate_nameKeyTyped(evt);
            }
        });
        jPanel1.add(txtinmate_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 270, 30));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 5));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Date & Time: ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Def. Attorney:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Location :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 60, 40));

        txtattorney.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtattorneyKeyTyped(evt);
            }
        });
        jPanel3.add(txtattorney, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 200, 30));
        jPanel3.add(txttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 200, 30));

        txtcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcityActionPerformed(evt);
            }
        });
        txtcity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcityKeyTyped(evt);
            }
        });
        jPanel3.add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("City :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, 40));

        txtlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlocationActionPerformed(evt);
            }
        });
        txtlocation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlocationKeyTyped(evt);
            }
        });
        jPanel3.add(txtlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Judge :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 50, 40));

        txtofficer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtofficerKeyTyped(evt);
            }
        });
        jPanel3.add(txtofficer, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Officer :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, 40));

        txtcourt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcourtKeyTyped(evt);
            }
        });
        jPanel3.add(txtcourt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 140, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Court:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 70, 40));

        txtjudge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtjudgeKeyTyped(evt);
            }
        });
        jPanel3.add(txtjudge, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 170, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Transilator :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 40));

        txttrans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttransKeyTyped(evt);
            }
        });
        jPanel3.add(txttrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 200, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Prosecutor :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 70, 40));

        txtpros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprosKeyTyped(evt);
            }
        });
        jPanel3.add(txtpros, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 200, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Comment : ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 70, 40));

        txtcomment.setColumns(20);
        txtcomment.setRows(5);
        jScrollPane2.setViewportView(txtcomment);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 220, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 770, 230));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellsbook/police2.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 120, 150));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 110, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        table_c.setBackground(new java.awt.Color(153, 153, 255));
        table_c.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        table_c.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        table_c.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date_Time", "Court", "Type"
            }
        ));
        jScrollPane1.setViewportView(table_c);
        table_c.getColumnModel().getColumn(2).setResizable(false);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 370, 80));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 5, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btdelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btdelete.setText("DELETE");
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        btadd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btadd.setText("ADD");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });
        jPanel2.add(btadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 70, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 600, 140));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 540));

        setSize(new java.awt.Dimension(829, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtinmate_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinmate_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinmate_nameActionPerformed

    private void txtcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed

        
        
        ((DefaultTableModel)table_c.getModel()).removeRow(table_c.getSelectedRow());
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btdeleteActionPerformed

    private void txtlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlocationActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        
     Reset();   
        
        
                
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed

        
        // TODO add your handling code here:
        
        try {

            con=Connection1.ConnectDB();
            String sql = "INSERT INTO court"
            +"(inmate_name, DA, date_time, court_name, officer, judge,city,location, prosecutor,trans, comment)"

            +"values(?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setString(1, txtinmate_name.getText());
            pstm.setString(2, txtattorney.getText());

            pstm.setString(3, txttime.getText());
            pstm.setString(4, txtcourt.getText());

                        
             pstm.setString(5, txtofficer.getText());
             
            pstm.setString(6, txtjudge.getText());
            pstm.setString(7, txtcity.getText());
            
            pstm.setString(8, txtlocation.getText());

            pstm.setString(9, txtpros.getText());    
            
            pstm.setString(10, txttrans.getText());
             pstm.setString(11, txtcomment.getText());
            

            pstm.executeUpdate();

            JOptionPane.showMessageDialog(this, "YOUR DATA ADDED AND INSERTED SUCCESSFULLY");
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

               Update_table();
        
    }//GEN-LAST:event_btaddActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        dispose();
        mainC m = new mainC ();
        m.setVisible(true);
        
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txttransKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttransKeyTyped

        char c=evt.getKeyChar();
      if (!(Character.isLetter(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
    }          
        // TODO add your handling code here:
    }//GEN-LAST:event_txttransKeyTyped

    private void txtofficerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtofficerKeyTyped

        char c=evt.getKeyChar();
      if (!(Character.isDigit(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
    }          
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtofficerKeyTyped

    private void txtprosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprosKeyTyped

        char c=evt.getKeyChar();
      if (!(Character.isLetter(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
    }          
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprosKeyTyped

    private void txtcourtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcourtKeyTyped

        char c=evt.getKeyChar();
      if (!(Character.isLetter(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
    }          
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcourtKeyTyped

    private void txtcityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcityKeyTyped

        char c=evt.getKeyChar();
      if (!(Character.isLetter(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
    }          
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityKeyTyped

    private void txtinmate_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinmate_nameKeyTyped
char c=evt.getKeyChar();
      if (!(Character.isLetter(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(null, "ENTER ONLY LETTERS");
    }          
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinmate_nameKeyTyped

    private void txtjudgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjudgeKeyTyped

        char c=evt.getKeyChar();
      if (!(Character.isLetter(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(null, "ENTER ONLY LETTERS");
    }          
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjudgeKeyTyped

    private void txtattorneyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtattorneyKeyTyped

        
       char c=evt.getKeyChar();
      if (!(Character.isLetter(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(null, "ENTER ONLY LETTERS");
    }          
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtattorneyKeyTyped

    private void txtlocationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlocationKeyTyped

        char c=evt.getKeyChar();
      if (!(Character.isLetter(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(null, "ENTER ONLY LETTERS");
    }          
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlocationKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(court_appear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(court_appear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(court_appear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(court_appear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new court_appear().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_c;
    private javax.swing.JTextField txtattorney;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextArea txtcomment;
    private javax.swing.JTextField txtcourt;
    private javax.swing.JTextField txtinmate_name;
    private javax.swing.JTextField txtjudge;
    private javax.swing.JTextField txtlocation;
    private javax.swing.JTextField txtofficer;
    private javax.swing.JTextField txtpros;
    private javax.swing.JTextField txttime;
    private javax.swing.JTextField txttrans;
    // End of variables declaration//GEN-END:variables

    private void section() {
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("police.png")));
    }
}
