/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cellsbook;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.*;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author PRINCE
 */
public class inmate_visitor_log extends javax.swing.JFrame {
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form inmate_visitor_log
     */
    public inmate_visitor_log() {
        initComponents();
        section();
         
       
    
    }

    
    private void Update_table ()
{
        try {
            con=Connection1.ConnectDB();
            String sql = "select date_time ,name,relation  from inmate_visit";
            PreparedStatement pstm =con.prepareStatement(sql);
            rs=pstm.executeQuery(sql);
            v_table.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception ex) {
         JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    
}
      
    
        private void Reset()
{
    txt_inmatename.setText("");
    txt_name.setText("");
    
    
    txt_relate.setText("");
    //txt_date.setText("");
    txt_duration.setText("");
    txt_add.setText("");
   
    
     txt_phone.setText("");
     txt_city.setText("");
 
    txt_officer.setText("");
    
}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_inmatename = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        v_table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_city = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_officer = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_relate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_add = new javax.swing.JTextArea();
        txt_duration = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dba = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("INMATE MANAGEMENT SYSTEM (TANOSO POLICE STATION)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 43));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txt_inmatename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_inmatenameActionPerformed(evt);
            }
        });
        txt_inmatename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_inmatenameKeyTyped(evt);
            }
        });
        jPanel1.add(txt_inmatename, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 250, 30));

        v_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date_Time", "Duration", "Relation"
            }
        ));
        jScrollPane1.setViewportView(v_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 370, 80));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 5, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 70, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 600, 140));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 5));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Date: ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Name:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Address");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, 40));

        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nameKeyTyped(evt);
            }
        });
        jPanel3.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 200, 30));

        txt_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cityActionPerformed(evt);
            }
        });
        txt_city.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cityKeyTyped(evt);
            }
        });
        jPanel3.add(txt_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("City :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, 40));
        jPanel3.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 160, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Phone :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 50, 40));

        txt_officer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_officerKeyTyped(evt);
            }
        });
        jPanel3.add(txt_officer, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 110, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Officer :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, 40));

        txt_relate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_relateKeyTyped(evt);
            }
        });
        jPanel3.add(txt_relate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 140, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Relationship:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 80, 40));

        txt_add.setColumns(20);
        txt_add.setRows(5);
        jScrollPane2.setViewportView(txt_add);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 140, 70));
        jPanel3.add(txt_duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 50, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Duration :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 70, 40));
        jPanel3.add(dba, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 170, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 770, 180));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellsbook/police2.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 120, 150));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 110, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 830, 500));

        setSize(new java.awt.Dimension(843, 551));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_inmatenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_inmatenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_inmatenameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 ((DefaultTableModel)v_table.getModel()).removeRow(v_table.getSelectedRow());
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cityActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Reset();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        dispose();
        mainC t = new mainC();
        t.setVisible(true);
                
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        // TODO add your handling code here:
        
        try {

            con=Connection1.ConnectDB();
            String sql = "INSERT INTO inmate_visit"
            +"(inmate_name,name,relation,officer,date_time,duration,addr,phone,city)"

            +"values(?,?,?,?,?,?,?,?,?)";

            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setString(1, txt_inmatename.getText());
            pstm.setString(2, txt_name.getText());

            pstm.setString(3, txt_relate.getText());
            pstm.setString(4, txt_officer.getText());

             pstm.setString(5, ((JTextField)dba.getDateEditor().getUiComponent()).getText());
         
                        
             //pstm.setString(5, txt_date.getText());
             
            pstm.setString(6, txt_duration.getText());
            pstm.setString(7, txt_add.getText());
            
            pstm.setString(8, txt_phone.getText());

            pstm.setString(9, txt_city.getText());    
            
           
            pstm.executeUpdate();

            JOptionPane.showMessageDialog(this, "YOUR DATA ADDED AND INSERTED SUCCESSFULLY");
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        
       Update_table();
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyTyped
char c=evt.getKeyChar();
      if (!(Character.isLetter(c)|| (c== KeyEvent.VK_SPACE)||(c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(null, " PLEASE ENTER ONLY  LETTERS!!");
    }          
        // TODO add your handling code here:L
    }//GEN-LAST:event_txt_nameKeyTyped

    private void txt_officerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_officerKeyTyped

        char c=evt.getKeyChar();
      if (!(Character.isDigit(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c== KeyEvent.VK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(null, " PLEASE ENTER ONLY NUMBERS !!");
    }          
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_officerKeyTyped

    private void txt_relateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_relateKeyTyped

        char c=evt.getKeyChar();
      if (!(Character.isLetter(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c== KeyEvent.VK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(null, " PLEASE ENTER ONLY LETTERS !!");
    }          
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_relateKeyTyped

    private void txt_inmatenameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_inmatenameKeyTyped

        char c=evt.getKeyChar();
      if (!(Character.isLetter(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c== KeyEvent.VK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(null, " PLEASE ENTER ONLY LETTERS !!");
    }          
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_inmatenameKeyTyped

    private void txt_cityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cityKeyTyped
char c=evt.getKeyChar();
      if (!(Character.isLetter(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c== KeyEvent.VK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(null, " PLEASE ENTER ONLY NUMBERS !!");
    }          
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cityKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inmate_visitor_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inmate_visitor_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inmate_visitor_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inmate_visitor_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inmate_visitor_log().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dba;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_add;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_duration;
    private javax.swing.JTextField txt_inmatename;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_officer;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_relate;
    private javax.swing.JTable v_table;
    // End of variables declaration//GEN-END:variables

    private void section() {
       
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("police.png")));
         
       
    }
}
