/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cellsbook;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.*;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author PRINCE
 */
public class inmate_dis extends javax.swing.JFrame {
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    /**
     * Creates new form inmate_dis
     */
    public inmate_dis() {
        initComponents();
        section();
        
    }
    
    
   private  void Reset (){
       txt_bill.setText("");
       txt_h.setText("");
       name2.setText("");
       txt_sign.setText("");
       txt_native.setText("");
       txt_remark.setText("");
       txt_officer.setText("");
       txt_whom.setText("");
       txt_marks.setText("");
      // date4.setText("");
       nmp_combo.setSelectedItem("");
       nbc_combo.setSelectedItem("");
       
       
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txt_h = new javax.swing.JTextField();
        txt_native = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        txt_bill = new javax.swing.JTextField();
        txt_sign = new javax.swing.JTextField();
        nbc_combo = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_marks = new javax.swing.JTextArea();
        nmp_combo = new javax.swing.JComboBox();
        dba = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txt_officer = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_whom = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_remark = new javax.swing.JTextArea();
        btnew = new javax.swing.JButton();
        btsave = new javax.swing.JButton();
        bt_back = new javax.swing.JButton();
        con_cmb = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INMATE MANAGEMENT SYSTEM (TANOSO POLICE STATION)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 43));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("INMATE BILL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 190, 44));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inmate Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.setName("Teachers Info"); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("BILL No,");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 33, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Time");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Name: ");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Number of Hours in Cell");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Native of:");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setText("Number of meals Provided");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("Fresh Mark of voilence upon Prisoners arrest ");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 260, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("Signature/Marks");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, 34));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("Date When Librated");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 34));

        txt_h.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txt_h.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hActionPerformed(evt);
            }
        });
        jPanel3.add(txt_h, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 113, 30));

        txt_native.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txt_native.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_native.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nativeActionPerformed(evt);
            }
        });
        txt_native.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nativeKeyTyped(evt);
            }
        });
        jPanel3.add(txt_native, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 236, 30));

        name2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        name2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name2ActionPerformed(evt);
            }
        });
        name2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                name2KeyTyped(evt);
            }
        });
        jPanel3.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 270, 30));

        txt_bill.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txt_bill.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_billActionPerformed(evt);
            }
        });
        txt_bill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_billKeyTyped(evt);
            }
        });
        jPanel3.add(txt_bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 113, 30));

        txt_sign.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txt_sign.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_signActionPerformed(evt);
            }
        });
        jPanel3.add(txt_sign, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 236, 30));

        nbc_combo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nbc_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 Hour", "2 Hours", "3 Hours", "4 Hours", "5 Hours", "6 Hours", "Days", "2 Day", "3 Day", "4 Day", " " }));
        jPanel3.add(nbc_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 110, -1));

        txt_marks.setColumns(20);
        txt_marks.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        txt_marks.setRows(5);
        txt_marks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(txt_marks);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 236, 60));

        nmp_combo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nmp_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "19", "10" }));
        jPanel3.add(nmp_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 80, -1));
        jPanel3.add(dba, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 170, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 450, 440));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inmate Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel41.setText("By Whom and Where Apprehended");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, 34));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel48.setText("Officer");
        jPanel4.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 60, 30));

        txt_officer.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txt_officer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_officer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_officerActionPerformed(evt);
            }
        });
        txt_officer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_officerKeyTyped(evt);
            }
        });
        jPanel4.add(txt_officer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 70, 30));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel49.setText("Remarks");
        jPanel4.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 70, 30));

        txt_whom.setColumns(20);
        txt_whom.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        txt_whom.setRows(5);
        txt_whom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txt_whom);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 190, 80));

        txt_remark.setColumns(20);
        txt_remark.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        txt_remark.setRows(5);
        txt_remark.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txt_remark);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 60, 190, 90));

        btnew.setBackground(new java.awt.Color(255, 255, 255));
        btnew.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnew.setText("NEW");
        btnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewActionPerformed(evt);
            }
        });
        jPanel4.add(btnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        btsave.setBackground(new java.awt.Color(255, 255, 255));
        btsave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btsave.setText("SAVE ");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });
        jPanel4.add(btsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        bt_back.setBackground(new java.awt.Color(0, 204, 255));
        bt_back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_back.setText("Back");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });
        jPanel4.add(bt_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        con_cmb.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        con_cmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Officer", "Insp. Yaw Kwame Nsia", "Cop. Appiah Prince", "Insp. Evelyn Narko ", "Supt. Osie Caleb", "Snr Supt. Antwi Bosiako", "Rt. Lt. Kwame Adu Kesse", "Cop. Emefah Domfeh ", "Insp. Ababio Richard ", "Mr. Asamoah Duodu", "Mad. Jane Amonu" }));
        con_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_cmbActionPerformed(evt);
            }
        });
        jPanel4.add(con_cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 200, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 370, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(836, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hActionPerformed

    private void txt_nativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nativeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nativeActionPerformed

    private void name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name2ActionPerformed

    private void txt_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_billActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_billActionPerformed

    private void txt_signActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_signActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_signActionPerformed

    private void txt_officerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_officerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_officerActionPerformed

    private void btnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewActionPerformed

        // code to rest
                Reset();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnewActionPerformed

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed

        try {

            con=Connection1.ConnectDB();
            String sql = "INSERT INTO bill_inmate"
            +"(bill_no,hr,name,DWL,NHC,NMP,fresh_mark,sign,native,Remarks,by_whom,officer)"

            +"values(?,?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement pstm = con.prepareStatement(sql);
                        pstm.setString(1, txt_bill.getText());
                        pstm.setString(2, txt_h.getText());
            
                       pstm.setString(4, ((JTextField)dba.getDateEditor().getUiComponent()).getText());
                        pstm.setString(3, name2.getText());
            
                        String combo1 = nbc_combo.getSelectedItem().toString();
                        pstm.setString(5, combo1);
            
                        String combo8 = nmp_combo.getSelectedItem().toString();
                        pstm.setString(6, combo8);
            
                        

                        pstm.setString(7, txt_marks.getText());
                        pstm.setString(8, txt_sign.getText());
            
                        pstm.setString(9, txt_native.getText());
                        pstm.setString(10, txt_remark.getText());
                        pstm.setString(11, txt_whom.getText());
                        pstm.setString(12, txt_officer.getText());

            pstm.executeUpdate();

            JOptionPane.showMessageDialog(this, "YOUR DATA INSERTED SUCCESSFULLY");
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btsaveActionPerformed

    private void txt_billKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_billKeyTyped

        
        char c=evt.getKeyChar();
      if (!(Character.isDigit(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c== KeyEvent.VK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
    }          
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_billKeyTyped

    private void name2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name2KeyTyped

        char c=evt.getKeyChar();
      if (!(Character.isLetter(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c== KeyEvent.VK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
    }          
        // TODO add your handling code here:
    }//GEN-LAST:event_name2KeyTyped

    private void txt_nativeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nativeKeyTyped

                char c=evt.getKeyChar();
      if (!(Character.isLetter(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c== KeyEvent.VK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
    }          
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nativeKeyTyped

    private void txt_officerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_officerKeyTyped

        //char c=evt.getKeyChar();
  
   
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_officerKeyTyped

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        dispose();
        mainC m = new mainC();
        m.setVisible(true);
    }//GEN-LAST:event_bt_backActionPerformed

    private void con_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_cmbActionPerformed

        if (  con_cmb.getSelectedItem().equals("Insp. Yaw Kwame Nsia")){

            txt_officer.setText("PY251");
        }
        else if (  con_cmb.getSelectedItem().equals("Cop. Appiah Prince")){

            txt_officer.setText("CT254");
        }
        else if (  con_cmb.getSelectedItem().equals("Insp. Evelyn Narko ")){

            txt_officer.setText("PY802");
        }
        else if (  con_cmb.getSelectedItem().equals("Supt. Osie Caleb")){

            txt_officer.setText("SP415");
        }
        else if (  con_cmb.getSelectedItem().equals("Snr Supt. Antwi Bosiako")){

            txt_officer.setText("PY026");
        }

        else if (  con_cmb.getSelectedItem().equals("Rt. Lt. Kwame Adu Kesse")){

            txt_officer.setText("RT097");
        }
        else if (  con_cmb.getSelectedItem().equals("Cop. Emefah Domfeh")){

            txt_officer.setText("PY408");
        }

        else if (  con_cmb.getSelectedItem().equals("Insp. Ababio Richard")){

            txt_officer.setText("PM051");
        }
        else if (  con_cmb.getSelectedItem().equals("Mr. Asamoah Duodu")){

            txt_officer.setText("SM503");
        }

        else if (  con_cmb.getSelectedItem().equals("Mad. Jane Amonu")){

            txt_officer.setText("AW719");
           
        }
        else
            txt_officer.setText("");
        

        // TODO add your handling code here:
    }//GEN-LAST:event_con_cmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inmate_dis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inmate_dis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inmate_dis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inmate_dis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inmate_dis().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_back;
    private javax.swing.JButton btnew;
    private javax.swing.JButton btsave;
    private javax.swing.JComboBox con_cmb;
    private com.toedter.calendar.JDateChooser dba;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField name2;
    private javax.swing.JComboBox nbc_combo;
    private javax.swing.JComboBox nmp_combo;
    private javax.swing.JTextField txt_bill;
    private javax.swing.JTextField txt_h;
    private javax.swing.JTextArea txt_marks;
    private javax.swing.JTextField txt_native;
    private javax.swing.JTextField txt_officer;
    private javax.swing.JTextArea txt_remark;
    private javax.swing.JTextField txt_sign;
    private javax.swing.JTextArea txt_whom;
    // End of variables declaration//GEN-END:variables

    private void section() {
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("police.png")));
    }
}
