/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cellsbook;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.*;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author PRINCE
 */
public class inmate_reg extends javax.swing.JFrame {
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form inmate_reg
     */
    public inmate_reg() {
        initComponents();
        section();
    }
    
 String imagePath = null ;
    //resize image
    
    public ImageIcon ResizeImage(String imagePath, byte[] pic){
        
        ImageIcon myImage = null;
        
        if (imagePath != null){ 
            
            myImage = new ImageIcon(imagePath);
            
        } else {
            
            myImage = new ImageIcon(pic);
            
               }
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lpic1.getWidth(), lpic1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        
        
        return image;
        
                    }
    private void Reset()
{
    
    name2.setText("");
    name3.setText(""); 
    //dba.("");
    addr2.setText("");
    naid.setText("");
    txt_property.setText("");
    lpic1.setIcon(null);
    
     nativ.setText("");
     occup1.setText("");
     hr1.setText("");
    
    gcombo2.setSelectedIndex(0);
    
    mscombo2.setSelectedIndex(0);
    tel.setText("");
    txt_h.setText("");
    txt_crime.setText("");
    txt_eye.setText("");
    txt_hair.setText("");
    txt_w.setText("");
    txt_officer.setText("");
    
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        hr1 = new javax.swing.JTextField();
        nativ = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        occup1 = new javax.swing.JTextField();
        mscombo2 = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        addr2 = new javax.swing.JTextArea();
        gcombo2 = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        age1 = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        dba = new com.toedter.calendar.JDateChooser();
        jLabel40 = new javax.swing.JLabel();
        name3 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        btpic = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        naid = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txt_h = new javax.swing.JTextField();
        txt_w = new javax.swing.JTextField();
        lpic1 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txt_hair = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txt_officer = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txt_crime = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        txt_eye = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_property = new javax.swing.JTextArea();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        con_cmb = new javax.swing.JComboBox();
        btnew = new javax.swing.JButton();
        btsave = new javax.swing.JButton();
        bt_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INMATE MANAGEMENT SYSTEM (TANOSO POLICE STATION)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("INMATE BOOKING");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inmate Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.setName("Teachers Info"); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Time:");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Last Name:");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Marita Status");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 171, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Native of:");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setText("Gender");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 209, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("Age");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("Permanent Address");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 34));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("Contact Address");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 34));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("Occupation:");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 34));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("Date ");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 116, -1, 34));

        hr1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hr1ActionPerformed(evt);
            }
        });
        hr1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hr1KeyTyped(evt);
            }
        });
        jPanel3.add(hr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 113, -1));

        nativ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nativ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nativActionPerformed(evt);
            }
        });
        nativ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nativKeyTyped(evt);
            }
        });
        jPanel3.add(nativ, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 236, -1));

        name2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        name2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name2ActionPerformed(evt);
            }
        });
        name2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                name2KeyTyped(evt);
            }
        });
        jPanel3.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 223, -1));

        occup1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        occup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occup1ActionPerformed(evt);
            }
        });
        jPanel3.add(occup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 236, -1));

        mscombo2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mscombo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Divorce", "Married", " " }));
        jPanel3.add(mscombo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 236, -1));

        addr2.setColumns(20);
        addr2.setRows(5);
        jScrollPane3.setViewportView(addr2);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 236, 60));

        gcombo2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gcombo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel3.add(gcombo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 236, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setText("or");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        age1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        age1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        age1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age1ActionPerformed(evt);
            }
        });
        age1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                age1KeyTyped(evt);
            }
        });
        jPanel3.add(age1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 40, -1));

        tel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telActionPerformed(evt);
            }
        });
        tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telKeyTyped(evt);
            }
        });
        jPanel3.add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 236, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel42.setText("Telephone Number");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, 34));
        jPanel3.add(dba, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("First Name: ");
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 74, 70, 10));

        name3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        name3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        name3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name3ActionPerformed(evt);
            }
        });
        name3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                name3KeyTyped(evt);
            }
        });
        jPanel3.add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 223, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inmate Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel41.setText("National ID/Passport No.");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 34));

        btpic.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btpic.setText("Add Picture");
        btpic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpicActionPerformed(evt);
            }
        });
        jPanel4.add(btpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 143, -1, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel44.setText("Weight");
        jPanel4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 30));

        naid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        naid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naidActionPerformed(evt);
            }
        });
        jPanel4.add(naid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 165, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel45.setText("Height");
        jPanel4.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 34));

        txt_h.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txt_h.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hActionPerformed(evt);
            }
        });
        txt_h.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_hKeyTyped(evt);
            }
        });
        jPanel4.add(txt_h, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 40, -1));

        txt_w.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txt_w.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_wActionPerformed(evt);
            }
        });
        txt_w.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_wKeyTyped(evt);
            }
        });
        jPanel4.add(txt_w, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 40, -1));

        lpic1.setBackground(new java.awt.Color(204, 204, 204));
        lpic1.setOpaque(true);
        jPanel4.add(lpic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 182, 113));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel46.setText("Kg");
        jPanel4.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 20, 20));

        txt_hair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_hair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hairActionPerformed(evt);
            }
        });
        jPanel4.add(txt_hair, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 110, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel47.setText("Eyes");
        jPanel4.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, 30));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel48.setText("Code");
        jPanel4.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 60, 30));

        txt_officer.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txt_officer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_officer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_officerActionPerformed(evt);
            }
        });
        txt_officer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_officerKeyTyped(evt);
            }
        });
        jPanel4.add(txt_officer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 80, 30));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel49.setText("Property found on Accused");
        jPanel4.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 190, 30));

        txt_crime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_crime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_crimeActionPerformed(evt);
            }
        });
        jPanel4.add(txt_crime, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 180, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel50.setText("Crime/ Offence");
        jPanel4.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 90, 30));

        txt_eye.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_eye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_eyeActionPerformed(evt);
            }
        });
        jPanel4.add(txt_eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 110, 20));

        txt_property.setColumns(20);
        txt_property.setRows(5);
        jScrollPane1.setViewportView(txt_property);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, 80));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel51.setText("Hair");
        jPanel4.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, 30));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel52.setText("Ft");
        jPanel4.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 20, 20));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel53.setText("Officer");
        jPanel4.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 60, 30));

        con_cmb.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        con_cmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Officer", "Insp. Yaw Kwame Nsia", "Cop. Appiah Prince", "Insp. Evelyn Narko ", "Supt. Osie Caleb", "Snr Supt. Antwi Bosiako", "Rt. Lt. Kwame Adu Kesse", "Cop. Emefah Domfeh ", "Insp. Ababio Richard ", "Mr. Asamoah Duodu", "Mad. Jane Amonu" }));
        con_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_cmbActionPerformed(evt);
            }
        });
        jPanel4.add(con_cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 200, -1));

        btnew.setBackground(new java.awt.Color(255, 255, 255));
        btnew.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnew.setText("NEW");
        btnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewActionPerformed(evt);
            }
        });

        btsave.setBackground(new java.awt.Color(255, 255, 255));
        btsave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btsave.setText("SAVE ");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });

        bt_back.setBackground(new java.awt.Color(0, 204, 255));
        bt_back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_back.setText("Back");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(bt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(btnew, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btsave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnew)
                    .addComponent(btsave)
                    .addComponent(bt_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72))
        );

        jPanel3.getAccessibleContext().setAccessibleName("Inmate ");

        setSize(new java.awt.Dimension(812, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hr1ActionPerformed

    private void nativActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nativActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nativActionPerformed

    private void name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name2ActionPerformed

    private void occup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occup1ActionPerformed

    private void btpicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpicActionPerformed

        // code for adding picture
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.image","jpg","png");
        file.addChoosableFileFilter(filter);

        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = file.getSelectedFile();
            String path1 = selectedFile.getAbsolutePath();
            lpic1.setIcon(ResizeImage(path1,null));
            imagePath = path1;
        }else {

            System.out.println(" NO FILE IMAGE IS SELECTED");
        }
        
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btpicActionPerformed

    private void naidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_naidActionPerformed

    private void txt_hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hActionPerformed

    private void txt_wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_wActionPerformed

    private void btnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewActionPerformed

       
         Reset();

        
    }//GEN-LAST:event_btnewActionPerformed

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed

        try {

             con=Connection1.ConnectDB();
            
             //if (bkn.getText().equals("")) {
               // JOptionPane.showMessageDialog( this, "Please enter id","Error", JOptionPane.ERROR_MESSAGE);
                //return;

            //}
            if (hr1.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter hour","Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (name2.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter his/her name","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
           if ( txt_officer.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter officer no.","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
         
            if (age1.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter age","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
             if (gcombo2.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog( this, "Please select gender","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
           
            
                        
            
            String sql = "INSERT INTO inmate"
            +"(hr,fname,lname,dof,m_status,gender,age,address,occup,native,telephone,pic,national_id,height,weight,hair,officer,eyes,crime,property)"

            +"values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement pstm = con.prepareStatement(sql);
            //pstm.setString(1, bkn.getText());
            pstm.setString(1, hr1.getText());
            
            
            pstm.setString(4, ((JTextField)dba.getDateEditor().getUiComponent()).getText());
         
           
            pstm.setString(2, name2.getText());
            
            pstm.setString(3, name3.getText());

            InputStream img4 = new FileInputStream(new File(imagePath));
            pstm.setBlob(12, img4);
            
             pstm.setString(7, age1.getText());
             
            String combo1 = gcombo2.getSelectedItem().toString();
            
            pstm.setString(6, combo1);
            
            pstm.setString(14, txt_h.getText());
            pstm.setString(15, txt_w.getText());
            
            pstm.setString(16, txt_hair.getText());

            String combo8 = mscombo2.getSelectedItem().toString();
            pstm.setString(5, combo8);

            pstm.setString(17, txt_officer.getText());    
            
            pstm.setString(18, txt_eye.getText());
             pstm.setString(11, tel.getText());
            
            pstm.setString(20, txt_property.getText());
            pstm.setString(19, txt_crime.getText());

            pstm.setString(9, occup1.getText());
            pstm.setString(8, addr2.getText());
            pstm.setString(13, naid.getText());
            pstm.setString(10, nativ.getText());

            pstm.executeUpdate();
            

            JOptionPane.showMessageDialog(this, "YOUR DATA INSERT SUCCESSFULLY INTO YOUR DATABASE");
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
            
        }
          //Reset();
        // TODO add your handling code here:
    }//GEN-LAST:event_btsaveActionPerformed

    private void txt_hairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hairActionPerformed

    private void age1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age1ActionPerformed

    private void txt_officerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_officerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_officerActionPerformed

    private void txt_crimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_crimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_crimeActionPerformed

    private void txt_eyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_eyeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_eyeActionPerformed

    private void telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telActionPerformed

    private void txt_hKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hKeyTyped

        char c=evt.getKeyChar();
      if (!(Character.isDigit(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c== KeyEvent.VK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
           JOptionPane.showMessageDialog(null, " PLEASE ENTER ONLY NUMBERS !!");
    }          
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hKeyTyped

    private void txt_wKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_wKeyTyped
char c=evt.getKeyChar();
      if (!(Character.isDigit(c)|| (c== KeyEvent.VK_SPACE)||(c== KeyEvent.VK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(null, " PLEASE ENTER ONLY NUMBERS !!");
    }          
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_wKeyTyped

    private void name2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name2KeyTyped

        char c=evt.getKeyChar();
      if (!(Character.isLetter(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c== KeyEvent.VK_SPACE)||(c==KeyEvent.VK_SPACE))){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(null, " PLEASE ENTER ONLY LETTERS !!");
    }          
        // TODO add your handling code here:
    }//GEN-LAST:event_name2KeyTyped

    private void age1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age1KeyTyped
       
        char c=evt.getKeyChar();
      if (!(Character.isDigit(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c== KeyEvent.VK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
           JOptionPane.showMessageDialog(null, " PLEASE ENTER ONLY NUMBERS !!");
    }          
        // TODO add your handling code here:
    }//GEN-LAST:event_age1KeyTyped

    private void telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyTyped

        char c=evt.getKeyChar();
      if (!(Character.isDigit(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c== KeyEvent.VK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(null, " PLEASE ENTER ONLY NUMBERS !!");
    }          
        // TODO add your handling code here:
    }//GEN-LAST:event_telKeyTyped

    private void txt_officerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_officerKeyTyped

       // char c=evt.getKeyChar();
 
        
            
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_officerKeyTyped

    private void nativKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nativKeyTyped

        char c=evt.getKeyChar();
      if (!(Character.isLetter(c)||(c== KeyEvent.VK_SHIFT)|| (c== KeyEvent.VK_BACK_SPACE)||(c== KeyEvent.VK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(null, " PLEASE ENTER ONLY LETTERS !!");
    }          
        // TODO add your handling code here:
    }//GEN-LAST:event_nativKeyTyped

    private void hr1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hr1KeyTyped

        //char c=evt.getKeyChar();
              
        // TODO add your handling code here:
    }//GEN-LAST:event_hr1KeyTyped

    private void con_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_cmbActionPerformed

         if (  con_cmb.getSelectedItem().equals("Insp. Yaw Kwame Nsia")){
            
            txt_officer.setText("PY251");
        }
        else if (  con_cmb.getSelectedItem().equals("Cop. Appiah Prince")){
            
             txt_officer.setText("CT254");
        }
        else if (  con_cmb.getSelectedItem().equals("Insp. Evelyn Narko ")){
            
             txt_officer.setText("PY802");
        }
        else if (  con_cmb.getSelectedItem().equals("Supt. Osie Caleb")){
            
             txt_officer.setText("SP415");
        }
        else if (  con_cmb.getSelectedItem().equals("Snr Supt. Antwi Bosiako")){
            
             txt_officer.setText("PY026");
        }
        
          else if (  con_cmb.getSelectedItem().equals("Rt. Lt. Kwame Adu Kesse")){
            
             txt_officer.setText("RT097");
        }
         else if (  con_cmb.getSelectedItem().equals("Cop. Emefah Domfeh")){
            
             txt_officer.setText("PY408");
        }
        
          else if (  con_cmb.getSelectedItem().equals("Insp. Ababio Richard")){
            
             txt_officer.setText("PM051");
        }
          else if (  con_cmb.getSelectedItem().equals("Mr. Asamoah Duodu")){
            
             txt_officer.setText("SM503");
        }
         
          else if (  con_cmb.getSelectedItem().equals("Mad. Jane Amonu")){
            
             txt_officer.setText("AW719");
        }
         else
            txt_officer.setText("");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_con_cmbActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        dispose();
        mainC m = new mainC();
        m.setVisible(true);
    }//GEN-LAST:event_bt_backActionPerformed

    private void name3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name3ActionPerformed

    private void name3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_name3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inmate_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inmate_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inmate_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inmate_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inmate_reg().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addr2;
    private javax.swing.JTextField age1;
    private javax.swing.JButton bt_back;
    private javax.swing.JButton btnew;
    private javax.swing.JButton btpic;
    private javax.swing.JButton btsave;
    private javax.swing.JComboBox con_cmb;
    private com.toedter.calendar.JDateChooser dba;
    private javax.swing.JComboBox gcombo2;
    private javax.swing.JTextField hr1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lpic1;
    private javax.swing.JComboBox mscombo2;
    private javax.swing.JTextField naid;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField name3;
    private javax.swing.JTextField nativ;
    private javax.swing.JTextField occup1;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField txt_crime;
    private javax.swing.JTextField txt_eye;
    private javax.swing.JTextField txt_h;
    private javax.swing.JTextField txt_hair;
    private javax.swing.JTextField txt_officer;
    private javax.swing.JTextArea txt_property;
    private javax.swing.JTextField txt_w;
    // End of variables declaration//GEN-END:variables

    private void section() {
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("police.png")));
    }
}
